export const COUNTRIES: { code: string; name: string }[] = [
  // Europe
  { code: "BE", name: "Belgique" },
  { code: "FR", name: "France" },
  { code: "CH", name: "Suisse" },
  { code: "LU", name: "Luxembourg" },
  { code: "DE", name: "Allemagne" },
  { code: "NL", name: "Pays-Bas" },
  { code: "GB", name: "Royaume-Uni" },
  { code: "ES", name: "Espagne" },
  { code: "IT", name: "Italie" },
  { code: "PT", name: "Portugal" },
  { code: "AT", name: "Autriche" },
  { code: "PL", name: "Pologne" },
  { code: "SE", name: "Suède" },
  { code: "NO", name: "Norvège" },
  { code: "DK", name: "Danemark" },
  { code: "FI", name: "Finlande" },
  { code: "IE", name: "Irlande" },
  { code: "GR", name: "Grèce" },
  { code: "CZ", name: "République tchèque" },
  { code: "HU", name: "Hongrie" },
  { code: "RO", name: "Roumanie" },
  { code: "BG", name: "Bulgarie" },
  { code: "HR", name: "Croatie" },
  { code: "SK", name: "Slovaquie" },
  { code: "SI", name: "Slovénie" },
  { code: "EE", name: "Estonie" },
  { code: "LV", name: "Lettonie" },
  { code: "LT", name: "Lituanie" },
  { code: "CY", name: "Chypre" },
  { code: "MT", name: "Malte" },
  // Afrique francophone
  { code: "CM", name: "Cameroun" },
  { code: "SN", name: "Sénégal" },
  { code: "CI", name: "Côte d'Ivoire" },
  { code: "ML", name: "Mali" },
  { code: "BF", name: "Burkina Faso" },
  { code: "GN", name: "Guinée" },
  { code: "BJ", name: "Bénin" },
  { code: "NE", name: "Niger" },
  { code: "TG", name: "Togo" },
  { code: "GA", name: "Gabon" },
  { code: "CD", name: "Congo (RDC)" },
  { code: "CG", name: "Congo (Brazzaville)" },
  { code: "MG", name: "Madagascar" },
  { code: "MA", name: "Maroc" },
  { code: "TN", name: "Tunisie" },
  { code: "DZ", name: "Algérie" },
  { code: "MR", name: "Mauritanie" },
  { code: "CF", name: "Centrafrique" },
  { code: "TD", name: "Tchad" },
  { code: "RW", name: "Rwanda" },
  { code: "BI", name: "Burundi" },
  { code: "KM", name: "Comores" },
  { code: "DJ", name: "Djibouti" },
  { code: "MU", name: "Maurice" },
  { code: "SC", name: "Seychelles" },
  // Afrique anglophone/lusophone
  { code: "NG", name: "Nigeria" },
  { code: "GH", name: "Ghana" },
  { code: "KE", name: "Kenya" },
  { code: "ZA", name: "Afrique du Sud" },
  { code: "ET", name: "Éthiopie" },
  { code: "TZ", name: "Tanzanie" },
  { code: "UG", name: "Ouganda" },
  { code: "EG", name: "Égypte" },
  { code: "AO", name: "Angola" },
  { code: "MZ", name: "Mozambique" },
  { code: "ZM", name: "Zambie" },
  { code: "ZW", name: "Zimbabwe" },
  // Amériques
  { code: "US", name: "États-Unis" },
  { code: "CA", name: "Canada" },
  { code: "MX", name: "Mexique" },
  { code: "BR", name: "Brésil" },
  { code: "AR", name: "Argentine" },
  { code: "CO", name: "Colombie" },
  { code: "CL", name: "Chili" },
  { code: "PE", name: "Pérou" },
  { code: "VE", name: "Venezuela" },
  { code: "EC", name: "Équateur" },
  { code: "BO", name: "Bolivie" },
  { code: "PY", name: "Paraguay" },
  { code: "UY", name: "Uruguay" },
  { code: "HT", name: "Haïti" },
  { code: "GP", name: "Guadeloupe" },
  { code: "MQ", name: "Martinique" },
  { code: "GF", name: "Guyane française" },
  { code: "RE", name: "La Réunion" },
  // Asie / Moyen-Orient
  { code: "CN", name: "Chine" },
  { code: "JP", name: "Japon" },
  { code: "IN", name: "Inde" },
  { code: "KR", name: "Corée du Sud" },
  { code: "TR", name: "Turquie" },
  { code: "SA", name: "Arabie Saoudite" },
  { code: "AE", name: "Émirats arabes unis" },
  { code: "IL", name: "Israël" },
  { code: "LB", name: "Liban" },
  { code: "SG", name: "Singapour" },
  { code: "TH", name: "Thaïlande" },
  { code: "VN", name: "Vietnam" },
  { code: "ID", name: "Indonésie" },
  { code: "PH", name: "Philippines" },
  { code: "PK", name: "Pakistan" },
  { code: "BD", name: "Bangladesh" },
  // Océanie
  { code: "AU", name: "Australie" },
  { code: "NZ", name: "Nouvelle-Zélande" },
];
